[build]
  publish = "."             # root directory (where index.html is)
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "."
  envFiles = [".env"]       # only used locally
